spring:
  application:
    name: capitole-challenge
  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: sa
    password: sa
    properties:
      logging:
        level: TRACE
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true # Formatea las consultas SQL en el log
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
      schema-locations: classpath:h2config/schema.sql
      data-locations: classpath:h2config/data.sql

logging:
  level:
    io:
      r2dbc:
        h2: DEBUG
        spi:
          ConnectionFactory: DEBUG
    org:
      springframework:
        data:
          r2dbc:
            core: DEBUG
        r2dbc:
          core: DEBUG